cron:
  schedule: "*/1 * * * *"

config:
  broker: rabbitmq.standup.svc.cluster.local
  organization: "https://dev.azure.com/hugginsio/"
  pat: replace-in-overlay
  wiql: "SELECT [System.Id], [System.Title], [System.State], [System.AssignedTo] FROM workitems WHERE [System.AssignedTo] = '&user;' ORDER BY [System.ChangedDate] DESC"

members:
  - name: Kyle
    id: Kyle Huggins <kyle@huggins.io>
  - name: First
    id: First Last <firstlast@huggins.io>

image:
  repository: data-extractor
  pullPolicy: IfNotPresent
  tag: "local"

resources:
  requests:
    cpu: 1m
    memory: 16Mi
  limits:
    memory: 16Mi
