[package]
name = "listener"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
