apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: listener
build:
  local:
    push: false
  artifacts:
    - image: listener
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - listener
deploy:
  helm:
    releases:
      - name: listener
        namespace: standup
        createNamespace: true
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          setValueTemplates:
            image.repository: "{{.IMAGE_REPO_feature_flags}}"
            image.tag: "{{.IMAGE_TAG_feature_flags}}@{{.IMAGE_DIGEST_feature_flags}}"
