apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  ADO_DE_ORG: {{ .Values.config.organization }}
  BROKER: {{ .Values.config.broker }}
  WIQL: {{ .Values.config.wiql }}
