apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  AZURE_DEVOPS_EXT_PAT: {{b64enc .Values.config.pat }}
