apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: feature-flags
build:
  local:
    push: false
  artifacts:
    - image: feature-flags
      docker:
        cacheFrom:
          - feature-flags
deploy:
  helm:
    releases:
      - name: feature-flags
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          setValueTemplates:
            image.repository: "{{.IMAGE_REPO_feature_flags}}"
            image.tag: "{{.IMAGE_TAG_feature_flags}}@{{.IMAGE_DIGEST_feature_flags}}"
