# https://helmfile.readthedocs.io/en/stable/
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 300
  force: true

repositories:
  - name: mongodb
    url: "https://mongodb.github.io/helm-charts"

releases:
  - name: rabbitmq
    namespace: standup
    chart: "oci://registry-1.docker.io/bitnamicharts/rabbitmq"
    version: 15.1.0
    values:
      - auth:
          password: rabbit
          securePassword: false
        persistence:
          size: 4Gi
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 256Mi
  - name: mdb
    namespace: standup
    chart: "mongodb/community-operator"
    version: 0.11.0
    values:
      - operator:
          watchNamespace: standup
  - name: grafana
    namespace: standup
    chart: "oci://registry-1.docker.io/bitnamicharts/grafana"
    version: 11.4.0
    values:
      - admin:
          user: admin
          password: admin
        plugins: "marcusolsson-json-datasource"
        persistence:
          size: 4Gi
