apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm.fullname" . }}-{{ .Values.config.name }}"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  AZURE_DEVOPS_EXT_PAT: {{b64enc .Values.config.pat }}
