# Default values for feature-flags.

replicaCount: 2

image:
  repository: feature-flags
  pullPolicy: IfNotPresent
  tag: "local"

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 1m
    memory: 6Mi
  limits:
    memory: 6Mi

livenessProbe:
  httpGet:
    path: "/gold-plating"
    port: http
readinessProbe:
  httpGet:
    path: "/gold-plating"
    port: http
